version: "3"
# project_name: expressfinalproject
services:
  mysql:
    
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      # - MYSQL_ALLOW_EMPTY_PASSWORD=""
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  app:
    image:  ghcr.io/isracoder/expressfinalproject:$GIT_VERSION
    restart: always 
    environment:
      - PORT=80
      # - DB_HOST=mysql
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - SECRET_KEY=$SECRET_KEY
      - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - REGION=$REGION
      - AWS_VERIFIED_SENDER=$AWS_VERIFIED_SENDER

    ports:
      - "80:80"
    # healthcheck:
    #   test: ["CMD", "curl", "http://localhost"]
    #   timeout: 20s
    #   retries: 5
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data:
