version: "3"

services:
  mysql:
    
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=FinalProject
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  app:
    image:  ghcr.io/isracoder/expressfinalproject:$GIT_VERSION
    restart: always 
    environment:
      - PORT=79
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=FinalProject
    ports:
      - "80:80"
    # healthcheck:
    #   test: ["CMD", "curl", "http://localhost"]
    #   timeout: 20s
    #   retries: 5
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data:
