version: "3"

services:
  mysql:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      # - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=FinalProject
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    profiles:
      - in_docker
    container_name: FinalProject
    build: .
    environment:
      - PORT=80
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=FinalProject
    ports:
      - "3000:80"
    # healthcheck:
    #   test: ["CMD", "curl", "http://localhost"]
    #   timeout: 20s
    #   retries: 5
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data:
