name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: print linux info
        run: cat /etc/lsb-release
      - name: set image version
        id: image-version
        run: echo "gitsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build the docker image
        run: docker build . --file Dockerfile --tag ghcr.io/isracoder/expressfinalproject:${{ steps.image-version.outputs.gitsha }}
      - name: Publish docker image
        run: docker push ghcr.io/isracoder/expressfinalproject:${{ steps.image-version.outputs.gitsha }}
      - name: configure docker host
        uses: khaledez/configure-docker-host@v1
        with:
          # ip of ec2 instance
          host: 18.193.118.190
          user: github
          ssh-private-key: ${{ secrets.DEP3_KEY }}
      - name: deploy
        run: docker compose -f docker-compose-prod.yml up -d
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          GIT_VERSION: ${{ steps.image-version.outputs.gitsha }}
      - name: print logs
        if: always()
        run: docker compose logs
